module LText.Internal.TypeSigParser.SkeltypeSig where

-- Haskell module generated by the BNF converter

import LText.Internal.TypeSigParser.AbstypeSig
import LText.Internal.TypeSigParser.ErrM
type Result = Err String

failure :: Show a => a -> Result
failure x = Bad $ "Undefined case: " ++ show x

transExpr :: Expr -> Result
transExpr x = case x of
  EArrow expr1 expr2  -> failure x
  EUnit  -> failure x
  ETerm str  -> failure x



