name:                ltext
version:             0.1.3
github:              "ltext/ltext"
license:             BSD3
author:              "Athan Clark"
maintainer:          "athan.clark@localcooking.com"
copyright:           "2018 (c) Local Cooking Inc."
category:            Text
synopsis:            "Parameterized file evaluator"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/template-dictionary#readme>

dependencies:
- base >= 4.11 && < 5
- attoparsec
- directory
- exceptions
- extra
- mtl
- pretty
- text
- transformers
- QuickCheck
- quickcheck-combinators >= 0.0.5
- quickcheck-instances
- unordered-containers

ghc-options:
  - -Wall

library:
  source-dirs: src

executables:
  ltext:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - ltext
    - optparse-applicative

tests:
  template-dictionary-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - ltext
    - tasty
    - tasty-quickcheck
    - quickcheck-instances
