name: ltext # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.1.4' # just for humans, typically '1.2+git' or '1.3.2'
summary: text file template engine # 79 char long summary
description: |
  ltext can treat any file as a function, and applies them to one another,
  achieving a general-purpose templating engine.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  ltext:
    plugin: nil
    # See 'snapcraft plugins'
    stage-packages:
      - libc-bin
      - libgmp10
