name: ltext # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
architectures: [amd64, arm64]
version: '0.1.4' # just for humans, typically '1.2+git' or '1.3.2'
title: 位text
summary: general-purpose text-file templating utility # 79 char long summary
description: |
  位text is a generic templating tool for any text file. For languages that
  don't support import-style code-reuse, it's common to just copy/paste.
  However, after a change is needed, that change must be replicated manually
  to every file needing it. With 位text, you parameterize the files themselves,
  and let 位text do the pasting. 
contact: 'athan.clark@gmail.com'
issues: 'https://github.com/ltext/ltext/issues'
icon: ltext.png
license: BSD-3-Clause
type: app
website: https://ltext.github.io
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  ltext:
    command: bin/ltext
    plugs:
      - home
      - removable-media
      - personal-files

parts:
  ltext:
    plugin: nil
    source: .
    build-environment:
      - PATH: "/root/.local/bin:$PATH"
    override-build: |
      which stack || curl -sSL https://get.haskellstack.org/ | sh 
      stack --version
      stack build
      stack install
    organize:
      "/root/.local/bin/ltext" : bin/ltext
    build-packages:
      - curl
      - libcurl4
    stage-packages:
      - libc-bin
      - libgmp10
